### ISSUE TITLE
Solution failed

### ISSUE THREAD

**Issue by AnLinkSoft** [jannikmi/extremitypathfinder#33]
polygon [(0.0, 0.0), (-2.136, -1.71), (1.273, -7.556), (2.713, -6.518)]
start (2.713, -6.518)
end (-2.136, -1.71)

**Comment by jannikmi** [comment]
Since the points you provide as start and end points are also vertices of the polygon, the output is undefined.
It is unclear if polygon vertex lies outside or inside of a polygon and hence also weather a path from one to the other should be possible.
Does that help? Feel free to reopen the issue.

**Comment by AnLinkSoft** [comment]
So can we assume that these points are inside the polygon?
Else we can't get a solution for that situation.

**Comment by jannikmi** [comment]
Good idea. I am not any more if there were any reasons for me not to implement it in this way in the first place.
Feel free to create a merge request addressing #35
