### ISSUE TITLE
Assume vertices lie within the boundary polygon

### ISSUE THREAD

**Issue by jannikmi** [jannikmi/extremitypathfinder#35]
as a solution to issue #33 

when a query point is equal to a vertex of the boundary polygon it should be assumed that this point lies within the polygon in order to enable paths.
ATTENTION: for hole polygons it must be assumed that vertices lie outside!

**Comment by jannikmi** [comment]
To solve this one must control how the core "inside_polygon" test handles the case where vertices of the polynomial are identical to the query point.

**Comment by AnLinkSoft** [comment]
Hi, I'd like to use `shapely` to find out the nearest point if start or end point outside the polygon.
Shapely will return these points which lie in the edge of polygon.
So I think it's necessary to assume that.

**Comment by jannikmi** [comment]
This has already been implemented in the latest releases. Cf. https://github.com/jannikmi/extremitypathfinder/blob/b59a4290de7b36022d756cea6c79ee1b962f3e24/extremitypathfinder/utils.py#L132
