### ISSUE TITLE
Visibility graph ignoring boundary or holes in some cases

### ISSUE THREAD

**Issue by vergilijus** [jannikmi/extremitypathfinder#47]
Hello!

It seems that visibility graph ignoring outer boundary or holes in some cases and it leads to impossible shortest paths.

**Example with ignored boundary**
![map_plot_1659535886](https://user-images.githubusercontent.com/5514345/182634627-dce4d9db-34dd-4c09-824d-19642b390bf3.png)
![graph_path_plot_16595359](https://user-images.githubusercontent.com/5514345/182634763-af912849-69c5-4407-9248-c833b766ce71.png)

**Example with ignored hole**
![map_plot_1659536047](https://user-images.githubusercontent.com/5514345/182635518-8dcb827c-4a51-4f2e-980c-1b5ccde86dbf.png)
![prepared_map_plot_1659536047](https://user-images.githubusercontent.com/5514345/182635539-11bc80f0-087a-4d3e-8e96-f4ebb068aafc.png)

**One more example with ignored boundary**
![map_plot_1659536334](https://user-images.githubusercontent.com/5514345/182637561-13f24a5a-4774-4cf9-a9eb-4b45ab12a733.png)
![graph_path_plot_1659536337](https://user-images.githubusercontent.com/5514345/182637882-f7caec67-2928-43a9-8121-622c8465e2e5.png)

**Pickle files to reproduce issue**
[maps.zip](https://github.com/jannikmi/extremitypathfinder/files/9252453/maps.zip)

MacOS Monterey 12.5
Python 3.8.9
extremitypathfinder 2.2.2

**Comment by jannikmi** [comment]
Thanks for reporting this. Can you try with version 2.2.1 please? I might have introduced this behavior in the last release by mistake. 

Side request: The examples you gave are very good test environments. Would you mind sharing some scenarios?

**Comment by vergilijus** [comment]
With version 2.2.1 it works fine. Thank you for quick response!

I would like to share this scenarios, but i need to clarify the legal details first, i will answer you in few days.

**Comment by jannikmi** [comment]
Glad it works. I will remove release 2.2.2 soon. 

There is no need to use exactly this data. Feels free to obfuscate in whatever way required. Any kind of additional test  data would be highly appreciated. Thank you

**Comment by vergilijus** [comment]
I got approved for sharing data. There are about 20 maps like this that I can share.

**Comment by jannikmi** [comment]
> I got approved for sharing data. There are about 20 maps like this that I can share.

Could you add a PR with just including these maps?
