### ISSUE TITLE
Adding steps on path?

### ISSUE THREAD

**Issue by guimou** [jannikmi/extremitypathfinder#62]
Hi!
Right now, the algorithm takes the coordinates for the start and end points.
Would it be difficult to add an intermediary point (or several), and find the shortest path to go through them all? I can always try different options (length A->B->C vs A->C->B), but I was wondering if there could be a more elegant method that could be plugged directly in your algorithm.
Thanks!

Nice project btw, I will certainly use it in an upcoming demo of mine. I'll make sure to credit you.

**Comment by jannikmi** [comment]
Hello Guillaume, I am glad you like this project.

After the visibility graph has been built, this package finds the shortest path using the A* algorithm.

The natural solution for your problem would be to modify the A* algorithm:
* starting with all different (start, goal) combinations
* performing regular A* search, but not terminating when the goal node has been reached, but continuing to allow longer paths until all intermediary points are included in the path

This package is using the A* implementation from the `networkxz` library which AFAIK cannot be modified in the way described above.

What you can do however is using the pre-build visibility graph and then using it for this customised A* search:

```python
    env = PolygonEnvironment()
    env.store(*env_data)
    env.prepare()
    graph: nx.Graph = env.graph
    # add all extra nodes with visibility edges "manually"
    # perform custom A* search
```

So far there is no public method for computing the visible nodes from any given input point. That's something I will add in the next release for a more modular use of this package.

Hope this could help.

**Comment by guimou** [comment]
Thanks a lot for the detailed answer Jannik, that's very helpful. I won't say I understand everything as it's not my specialty at all, but at least enough to give it a try and figure it out.
Cheers!

**Comment by jannikmi** [comment]
You are welcome. Let me know which parts you get stuck with, then i can help.
