### ISSUE TITLE
Singular matrix

### ISSUE THREAD

**Issue by jfulem** [jannikmi/extremitypathfinder#64]
I have a pretty simple polygons:
![image](https://user-images.githubusercontent.com/14978902/199830917-6ed5de80-052b-4870-99f7-1f86562016f6.png)
But the shortest path is not found and I get a Singular Matrix error. 

Do you know why this is happening? Thanks.

**Comment by jannikmi** [comment]
Sorry, I somehow missed this issue. Thank you for posting this!
This is indeed strange and shouldn't happen.
Could you please open a PR including your test case (data). Then I can investigate.

**Comment by jannikmi** [comment]
@jfulem and please ensure that the data requirements are fulfilled, cf. https://extremitypathfinder.readthedocs.io/en/latest/1_usage.html#store-environment

**Comment by jfulem** [comment]
Hi @jannikmi, the requirements are fulfilled. I will try to provide you with the data as soon as possible.

**Comment by jannikmi** [comment]
@jfulem any update on this? It's hard for me to debug and fix the issue without your example data.

**Comment by jfulem** [comment]
I will take a look today or tomorrow.

**Comment by jannikmi** [comment]
Great, thanks!

**Comment by jannikmi** [comment]
@jfulem could you please post the stack trace of the error?
In order to fix the issue, I need to understand what kind of "Singular Matrix error" is being raised where and under what circumstances

**Comment by jannikmi** [comment]
I am closing this issue now due to inactivity. @jfulem feel free to post more details
