### ISSUE TITLE
Path going straight through hole

### ISSUE THREAD

**Issue by Ake-Wettergren** [jannikmi/extremitypathfinder#84]
I'm getting a path that runs straight through a hole. Technically it doesn't cross any of the edges of the hole, but runs along edges and crosses both in and out at vertices, so I gueses the issue is with checking edge crossings for visibility.

Setup to reproduce:

```
from extremitypathfinder.plotting import PlottingEnvironment

environment = PlottingEnvironment(plotting_dir="path\to\folder")

area = [(161.0, 47.0), (247.0, 47.0), (247.0, 7.0), (361.0, 7.0), (361.0, 441.0), (7.0, 441.0), (7.0, 7.0), (161.0, 7.0)]
holes = [[(272.0, 172.0), (272.0, 36.0), (136.0, 36.0), (136.0, 172.0), (155.6, 172.0), (155.6, 332.4), (252.4, 332.4), (252.4, 172.0)]]
(environment.graph, obj_dict) = PlottingEnvironment.get_graph(area, holes)
environment.save(obj_dict)

(start, end) = (50.004004, 44.004004), (318.004004, 44.004004)
sequence, sequence_length = environment.find_shortest_path(start, end)
```

![graph_path_plot_1701788345](https://github.com/jannikmi/extremitypathfinder/assets/119401020/dde52a0b-9f03-48b0-b26d-1780d57f74af)

**Comment by jannikmi** [comment]
Thanks for bringing up this important case! Unfortunately I don't have the time to look into it right now. Could you try adding  this as a test case for the visibility computation? Then one could more easily debug how this edge case can be handled.
